version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db:
    driver: local

